# Generated by Django 4.2.4 on 2023-09-13 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buy_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyerAuction', to=settings.AUTH_USER_MODEL),
        ),
    ]
